name: 'Weekly Sync with Upstream'

on:
  schedule:
    # Runs at 02:00 UTC on Sunday. Use https://crontab.guru to help generate cron schedules.
    - cron: '0 2 * * 0'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Fork'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Set Up Upstream'
        run: |
          git remote add upstream https://github.com/laravel/react-starter-kit.git
          git fetch upstream

      - name: 'Merge Upstream'
        run: |
          git checkout main
          git merge --ff-only upstream/main

      - name: 'Create Pull Request'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Sync with upstream'
          title: 'Update from laravel/react-starter-kit'
          body: |
            This PR updates the `main` branch with the latest changes from `laravel/react-starter-kit`.
          branch: 'upstream-sync'
          base: 'main'
          labels: 'automated-pr, upstream-sync'
          delete-branch: true
