name: typescript-transform

on:
  push:
  pull_request:

jobs:
  types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Server
        uses: ./.github/actions/setup-server

      - name: Check if TypeScript types are up to date
        run: |
          generated_types_file=$(mktemp)
          current_types_file="$GITHUB_WORKSPACE/resources/js/types/generated.d.ts"

          echo "Generating new types for comparison..."
          php artisan typescript:transform --silent --output="$generated_types_file" || true

          # First, check if the types file even exists in your repository.
          if [ ! -f "$current_types_file" ]; then
            echo "::error::The types file '$current_types_file' does not exist."
            echo "Please generate it for the first time by running 'php artisan typescript:transform' and commit the result."
            exit 1
          fi

          # Use the 'diff' command to compare the committed file with the generated one.
          # 'diff' will exit with a non-zero status code if the files are different.
          if ! diff -q "$current_types_file" "$generated_types_file"; then
            echo "::error::Generated TypeScript types are out of sync with the repository."
            echo "Please run 'php artisan typescript:transform' locally and commit the changes."
            
            echo "--- Differences ---"
            # Show the actual differences to make debugging easier
            diff -u "$current_types_file" "$generated_types_file" || true
            
            exit 1
          fi

          echo "✅ TypeScript types are up to date."
          exit 0
